# Generated by Django 3.2.10 on 2022-01-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=12)),
                ('DOB', models.DateField(default=None)),
                ('Salutation', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.CharField(max_length=10)),
                ('AddressLine1', models.CharField(max_length=50)),
                ('AddressLine2', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pin', models.CharField(max_length=7)),
                ('Country', models.CharField(max_length=50)),
            ],
        ),
    ]
