# Generated by Django 3.2.10 on 2022-01-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DOB',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
